export type BrokerEntry = {
  id: string;
  name: string;
  displayName: string;
  region: string;
  platform: string;
  execution: string;
  minDeposit: string;
  spread: string;
  highlight: string;
  description: string;
  tags: string[];
  categories: string[];
  accent: string;
  integration: 'PAPER' | 'MT4' | 'MT5';
  /** Pre-filled server names shown in the dropdown for this broker */
  servers?: string[];
};

export const BROKER_FILTERS = ['All', 'Favorites', 'Paper', 'MT4', 'MT5', 'ECN', 'STP', 'Beginner-friendly'] as const;
export const FEATURED_BROKERS = ['IC_MARKETS', 'PEPPERSTONE', 'EXNESS', 'XM', 'FXTM', 'PAPER'] as const;

export const BROKER_REGIONS = ['Global', 'US / Global', 'EU / Global', 'UK / Global', 'AU / Global'] as const;

export const BROKER_BRAND: Record<string, { mark: string; text: string; ring: string; badgeBg: string }> = {
  PAPER:        { mark: 'P',   text: 'text-emerald-200', ring: 'ring-chart-3/30', badgeBg: 'bg-chart-3/20' },
  IC_MARKETS:   { mark: 'IC',  text: 'text-cyan-100',    ring: 'ring-chart-5/30',    badgeBg: 'bg-chart-5/20'    },
  PEPPERSTONE:  { mark: 'PS',  text: 'text-violet-100',  ring: 'ring-chart-2/30',  badgeBg: 'bg-chart-2/20'  },
  EXNESS:       { mark: 'EX',  text: 'text-amber-100',   ring: 'ring-chart-4/30',   badgeBg: 'bg-chart-4/20'   },
  XM:           { mark: 'XM',  text: 'text-rose-100',    ring: 'ring-rose-300/30',    badgeBg: 'bg-destructive/20'    },
  FXTM:         { mark: 'FT',  text: 'text-indigo-100',  ring: 'ring-primary/30',  badgeBg: 'bg-primary/20'  },
  AVATRADE:     { mark: 'AV',  text: 'text-red-100',     ring: 'ring-red-300/30',     badgeBg: 'bg-red-500/20'     },
  FP_MARKETS:   { mark: 'FP',  text: 'text-chart-5',    ring: 'ring-chart-5/30',    badgeBg: 'bg-primary/20'    },
  TICKMILL:     { mark: 'TM',  text: 'text-cyan-100',    ring: 'ring-chart-5/30',    badgeBg: 'bg-chart-5/20'    },
  AXI:          { mark: 'AX',  text: 'text-purple-100',  ring: 'ring-purple-300/30',  badgeBg: 'bg-purple-500/20'  },
  HFM:          { mark: 'HF',  text: 'text-foreground',   ring: 'ring-slate-300/30',   badgeBg: 'bg-slate-500/20'   },
  BLACKBULL:    { mark: 'BB',  text: 'text-orange-100',  ring: 'ring-orange-300/30',  badgeBg: 'bg-orange-500/20'  },
  ROBOFOREX:    { mark: 'RF',  text: 'text-emerald-100', ring: 'ring-chart-3/30', badgeBg: 'bg-chart-3/20' },
  ADMIRALS:     { mark: 'AD',  text: 'text-yellow-100',  ring: 'ring-yellow-300/30',  badgeBg: 'bg-yellow-500/20'  },
  OANDA:        { mark: 'OA',  text: 'text-lime-100',    ring: 'ring-lime-300/30',    badgeBg: 'bg-lime-500/20'    },
  VANTAGE:      { mark: 'VFX', text: 'text-sky-100',     ring: 'ring-sky-300/30',     badgeBg: 'bg-sky-500/20'     },
  EIGHTCAP:     { mark: '8C',  text: 'text-teal-100',    ring: 'ring-teal-300/30',    badgeBg: 'bg-chart-3/20'    },
  FOREX_COM:    { mark: 'FX',  text: 'text-sky-100',     ring: 'ring-sky-300/30',     badgeBg: 'bg-sky-500/20'     },
  IG:           { mark: 'IG',  text: 'text-emerald-100', ring: 'ring-chart-3/30', badgeBg: 'bg-chart-3/20' },
  SWISSQUOTE:   { mark: 'SQ',  text: 'text-stone-100',   ring: 'ring-stone-300/30',   badgeBg: 'bg-stone-500/20'   },
};

export const BROKER_DIRECTORY: BrokerEntry[] = [
  {
    id: 'PAPER',
    name: 'Paper Trading',
    displayName: 'Paper Trading',
    region: 'Global',
    platform: 'Simulated',
    execution: 'Virtual / Instant',
    minDeposit: '$0',
    spread: 'Synthetic',
    highlight: 'Best for strategy testing',
    description: 'High-fidelity sandbox with virtual capital, no real market exposure, and instant fills.',
    tags: ['Demo', 'Risk-free', 'Backtest-ready'],
    categories: ['Paper', 'Beginner-friendly'],
    accent: 'from-chart-3/20 via-teal-400/10 to-transparent',
    integration: 'PAPER',
    servers: [],
  },
  // ── IC Markets ────────────────────────────────────────────────────────────
  {
    id: 'IC_MARKETS',
    name: 'IC Markets',
    displayName: 'IC Markets',
    region: 'AU / Global',
    platform: 'MT4 / MT5',
    execution: 'RAW ECN',
    minDeposit: '$200',
    spread: 'From 0.0 pips',
    highlight: 'Most popular ECN broker',
    description: 'Largest forex CFD broker by volume. True ECN with raw spreads from 0.0 pips and ultra-fast execution.',
    tags: ['ECN', 'Raw spread', 'HFT-friendly', 'Scalping'],
    categories: ['MT4', 'MT5', 'ECN'],
    accent: 'from-chart-5/20 via-chart-5/10 to-transparent',
    integration: 'MT5',
    servers: ['ICMarketsLive3-MT5', 'ICMarketsLive-MT5 3', 'ICMarkets-Live01', 'ICMarkets-Demo01'],
  },
  // ── Pepperstone ───────────────────────────────────────────────────────────
  {
    id: 'PEPPERSTONE',
    name: 'Pepperstone',
    displayName: 'Pepperstone',
    region: 'AU / Global',
    platform: 'MT4 / MT5',
    execution: 'NDD / ECN',
    minDeposit: '$0',
    spread: 'From 0.0 pips',
    highlight: 'Razor-thin spreads',
    description: 'Award-winning broker known for ultra-fast NDD execution, tight spreads, and deep liquidity pools.',
    tags: ['NDD', 'Low latency', 'Scalping', 'EA-ready'],
    categories: ['MT4', 'MT5', 'ECN', 'STP'],
    accent: 'from-chart-2/20 via-fuchsia-400/10 to-transparent',
    integration: 'MT5',
    servers: ['Pepperstone-Live', 'Pepperstone-Demo01', 'Pepperstone-Edge-Live', 'Pepperstone-Edge-Demo'],
  },
  // ── Exness ────────────────────────────────────────────────────────────────
  {
    id: 'EXNESS',
    name: 'Exness',
    displayName: 'Exness',
    region: 'Global',
    platform: 'MT4 / MT5',
    execution: 'Instant / Market',
    minDeposit: '$10',
    spread: 'Floating / Fixed',
    highlight: 'Unlimited leverage available',
    description: 'Offers instant withdrawals, high leverage options, and a wide range of account types for all trader levels.',
    tags: ['Flexible leverage', 'Instant withdrawal', 'Low deposit'],
    categories: ['MT4', 'MT5', 'Beginner-friendly'],
    accent: 'from-chart-4/20 via-orange-400/10 to-transparent',
    integration: 'MT5',
    servers: ['Exness-Real', 'Exness-Trial', 'ExnessServer', 'ExnessServer-MT5Real'],
  },
  // ── XM ────────────────────────────────────────────────────────────────────
  {
    id: 'XM',
    name: 'XM',
    displayName: 'XM',
    region: 'Global',
    platform: 'MT4 / MT5',
    execution: 'Market execution',
    minDeposit: '$5',
    spread: 'From 0.6 pips',
    highlight: 'No re-quotes, no rejection',
    description: 'Popular global broker with no re-quotes, micro accounts, and broad instrument coverage across 1000+ assets.',
    tags: ['No re-quotes', 'Micro accounts', 'Beginner-friendly'],
    categories: ['MT4', 'MT5', 'Beginner-friendly'],
    accent: 'from-pink-400/20 via-destructive/10 to-transparent',
    integration: 'MT5',
    servers: ['XMTrading-MT5', 'XMTrading-MT5 2', 'XMTrading-MT5 3', 'XMTrading-Demo'],
  },
  // ── FXTM ──────────────────────────────────────────────────────────────────
  {
    id: 'FXTM',
    name: 'FXTM',
    displayName: 'ForexTime',
    region: 'Global',
    platform: 'MT4 / MT5',
    execution: 'Market / Instant',
    minDeposit: '$10',
    spread: 'Variable',
    highlight: 'Flexible account levels',
    description: 'Regulated global broker offering ECN, STP and standard accounts with micro lot support for all experience levels.',
    tags: ['ECN', 'Micro lots', 'Bot ready'],
    categories: ['MT4', 'MT5', 'Beginner-friendly', 'ECN'],
    accent: 'from-primary/20 via-chart-5/10 to-transparent',
    integration: 'MT5',
    servers: ['ForexTimeFXTM-Real', 'ForexTimeFXTM-Demo', 'FXTM-Real 2', 'ForexTimeFXTM-Real ECN'],
  },
  // ── AvaTrade ──────────────────────────────────────────────────────────────
  {
    id: 'AVATRADE',
    name: 'AvaTrade',
    displayName: 'AvaTrade',
    region: 'Global',
    platform: 'MT4 / MT5',
    execution: 'Market execution',
    minDeposit: '$100',
    spread: 'Fixed / Floating',
    highlight: 'Fixed spreads available',
    description: 'Multi-regulated broker offering fixed and floating spreads, 250+ instruments, and auto-trading support.',
    tags: ['Fixed spreads', 'Multi-regulated', 'Auto-trading'],
    categories: ['MT4', 'MT5', 'STP', 'Beginner-friendly'],
    accent: 'from-destructive/20 via-red-400/10 to-transparent',
    integration: 'MT5',
    servers: ['AvaTrade-Real', 'AvaTrade-Demo', 'AvaTrade MT5 Real', 'AvaTrade MT5 Demo'],
  },
  // ── FP Markets ────────────────────────────────────────────────────────────
  {
    id: 'FP_MARKETS',
    name: 'FP Markets',
    displayName: 'FP Markets',
    region: 'AU / Global',
    platform: 'MT4 / MT5',
    execution: 'RAW ECN',
    minDeposit: '$100',
    spread: 'From 0.0 pips',
    highlight: 'Deep institutional liquidity',
    description: 'Australian-regulated ECN broker with institutional liquidity, sub-millisecond execution, and 10,000+ instruments.',
    tags: ['ECN', 'DMA', 'Raw pricing', 'Fast execution'],
    categories: ['MT4', 'MT5', 'ECN'],
    accent: 'from-chart-5/20 via-primary/10 to-transparent',
    integration: 'MT5',
    servers: ['FPMarkets-Live01', 'FPMarkets-Demo', 'FPMarkets-MT5-Real', 'FPMarkets-MT5-Demo'],
  },
  // ── Tickmill ──────────────────────────────────────────────────────────────
  {
    id: 'TICKMILL',
    name: 'Tickmill',
    displayName: 'Tickmill',
    region: 'EU / Global',
    platform: 'MT4 / MT5',
    execution: 'ECN / STP',
    minDeposit: '$100',
    spread: 'From 0.0 pips',
    highlight: 'Scalper & EA favorite',
    description: 'ECN-style execution with interbank liquidity, low commissions, and VPS support for algorithmic strategies.',
    tags: ['Scalping', 'ECN', 'Low commission', 'EA-friendly'],
    categories: ['MT4', 'MT5', 'ECN'],
    accent: 'from-chart-5/20 via-sky-400/10 to-transparent',
    integration: 'MT5',
    servers: ['Tickmill-Live', 'Tickmill-Demo', 'Tickmill-Live2', 'Tickmill-MT5 Live'],
  },
  // ── Axi ───────────────────────────────────────────────────────────────────
  {
    id: 'AXI',
    name: 'Axi',
    displayName: 'Axi',
    region: 'AU / Global',
    platform: 'MT4 / MT5',
    execution: 'Market execution',
    minDeposit: '$0',
    spread: 'From 0.0 pips',
    highlight: 'Zero min deposit',
    description: 'ASIC-regulated broker with 140+ FX pairs, free VPS, and a professional-grade MT4/MT5 execution environment.',
    tags: ['Zero deposit', 'VPS included', 'ASIC regulated'],
    categories: ['MT4', 'MT5', 'Beginner-friendly', 'ECN'],
    accent: 'from-purple-400/20 via-chart-2/10 to-transparent',
    integration: 'MT5',
    servers: ['Axi-Live', 'Axi-Demo', 'AxiTrader-Live', 'AxiTrader-Demo'],
  },
  // ── HFM ───────────────────────────────────────────────────────────────────
  {
    id: 'HFM',
    name: 'HFM',
    displayName: 'HF Markets',
    region: 'Global',
    platform: 'MT4 / MT5',
    execution: 'Market / ECN',
    minDeposit: '$5',
    spread: 'From 0.0 pips',
    highlight: 'Low-entry ECN access',
    description: 'CySEC and FCA regulated broker offering ECN execution from just $5, ideal for beginners and scalpers alike.',
    tags: ['Low deposit', 'ECN', 'Regulated', 'Bot ready'],
    categories: ['MT4', 'MT5', 'ECN', 'Beginner-friendly'],
    accent: 'from-slate-400/20 via-gray-400/10 to-transparent',
    integration: 'MT5',
    servers: ['HFMarketsGlobal-Demo02', 'HFMarketsGlobal-Live5', 'HFMarketsGlobal-Live6', 'HFMarketsGlobal-Live 1'],
  },
  // ── BlackBull ─────────────────────────────────────────────────────────────
  {
    id: 'BLACKBULL',
    name: 'BlackBull Markets',
    displayName: 'BlackBull',
    region: 'AU / Global',
    platform: 'MT4 / MT5',
    execution: 'True ECN',
    minDeposit: '$0',
    spread: 'From 0.0 pips',
    highlight: 'True ECN, no dealing desk',
    description: 'NZ-based ECN broker with no dealing desk, fast STP execution, and institutional-grade liquidity.',
    tags: ['True ECN', 'No DD', 'NDD', 'Raw pricing'],
    categories: ['MT4', 'MT5', 'ECN'],
    accent: 'from-orange-400/20 via-chart-4/10 to-transparent',
    integration: 'MT5',
    servers: ['BlackBull-Live 1', 'BlackBull-Demo', 'BlackBull Markets Live', 'BlackBull Markets Demo'],
  },
  // ── RoboForex ─────────────────────────────────────────────────────────────
  {
    id: 'ROBOFOREX',
    name: 'RoboForex',
    displayName: 'RoboForex',
    region: 'Global',
    platform: 'MT4 / MT5',
    execution: 'ECN / STP',
    minDeposit: '$10',
    spread: 'From 0.0 pips',
    highlight: 'Algo & EA optimized',
    description: 'Offshore broker popular with algorithmic traders for its ECN-Pro accounts, 8000+ instruments, and automated bot support.',
    tags: ['Algo-friendly', 'Bot ready', 'ECN-Pro', 'Low minimum'],
    categories: ['MT4', 'MT5', 'ECN', 'STP'],
    accent: 'from-teal-400/20 via-chart-3/10 to-transparent',
    integration: 'MT5',
    servers: ['RoboForex-Real', 'RoboForex-Demo', 'RoboForex-ECN-Real', 'RoboForex-Pro'],
  },
  // ── Admirals ──────────────────────────────────────────────────────────────
  {
    id: 'ADMIRALS',
    name: 'Admirals',
    displayName: 'Admirals',
    region: 'EU / Global',
    platform: 'MT4 / MT5',
    execution: 'Market / ECN',
    minDeposit: '$100',
    spread: 'From 0.0 pips',
    highlight: 'FCA & ASIC regulated',
    description: 'Multi-regulated European broker with 8000+ symbols, zero-spread account options, and free MetaTrader Supreme plugin.',
    tags: ['FCA regulated', 'Zero spread', 'MT Supreme'],
    categories: ['MT4', 'MT5', 'ECN', 'STP'],
    accent: 'from-yellow-400/20 via-chart-4/10 to-transparent',
    integration: 'MT5',
    servers: ['Admirals-Live5', 'Admirals-Demo', 'AdmiralMarkets-Live', 'AdmiralMarkets-Demo'],
  },
  // ── Vantage ───────────────────────────────────────────────────────────────
  {
    id: 'VANTAGE',
    name: 'Vantage',
    displayName: 'Vantage FX',
    region: 'AU / Global',
    platform: 'MT4 / MT5',
    execution: 'RAW ECN',
    minDeposit: '$50',
    spread: 'From 0.0 pips',
    highlight: 'Raw ECN from $50',
    description: 'ASIC-regulated broker with RAW ECN accounts from just $50, co-location servers, and automated bot support.',
    tags: ['RAW ECN', 'ASIC', 'Bot ready', 'Low commission'],
    categories: ['MT4', 'MT5', 'ECN'],
    accent: 'from-sky-400/20 via-chart-5/10 to-transparent',
    integration: 'MT5',
    servers: ['Vantage-Live', 'Vantage-Demo', 'VantageFX-Live', 'VantageFX-Demo'],
  },
  // ── Eightcap ──────────────────────────────────────────────────────────────
  {
    id: 'EIGHTCAP',
    name: 'Eightcap',
    displayName: 'Eightcap',
    region: 'AU / Global',
    platform: 'MT4 / MT5',
    execution: 'STP / ECN',
    minDeposit: '$100',
    spread: 'From 0.0 pips',
    highlight: 'Crypto + FX specialist',
    description: 'ASIC/SCB regulated broker offering forex, crypto CFDs, and indices with TradingView integration.',
    tags: ['Crypto CFDs', 'TradingView', 'ASIC', 'STP'],
    categories: ['MT4', 'MT5', 'ECN', 'STP'],
    accent: 'from-teal-400/20 via-chart-5/10 to-transparent',
    integration: 'MT5',
    servers: ['Eightcap-Live', 'Eightcap-Demo', 'EightcapLive-1', 'EightcapDemo-1'],
  },
  // ── OANDA ─────────────────────────────────────────────────────────────────
  {
    id: 'OANDA',
    name: 'OANDA',
    displayName: 'OANDA',
    region: 'US / Global',
    platform: 'MT4 / Web API',
    execution: 'Spread-only / NDD',
    minDeposit: '$0',
    spread: 'Transparent variable',
    highlight: 'Trusted US forex broker',
    description: 'Highly regulated US broker with a strong API, zero min deposit, and transparent spread pricing.',
    tags: ['US regulated', 'API-first', 'No min deposit'],
    categories: ['MT4', 'STP', 'Beginner-friendly'],
    accent: 'from-chart-3/20 via-lime-400/10 to-transparent',
    integration: 'MT4',
    servers: ['OANDA-v20 Live-1', 'OANDA-v20 Live-2', 'OANDA-v20 Practice', 'OANDA-fxTrade Practice'],
  },
  // ── IG ────────────────────────────────────────────────────────────────────
  {
    id: 'IG',
    name: 'IG',
    displayName: 'IG',
    region: 'UK / Global',
    platform: 'MT4 / Web',
    execution: 'DMA / Market',
    minDeposit: '$0',
    spread: 'Variable',
    highlight: 'UK\'s largest broker',
    description: 'World\'s No.1 CFD provider with DMA access to 17,000+ markets, deep liquidity, and 40+ years of history.',
    tags: ['DMA', 'FCA regulated', 'Global', '17k markets'],
    categories: ['MT4', 'DMA'],
    accent: 'from-chart-3/20 via-chart-5/10 to-transparent',
    integration: 'MT4',
    servers: ['IG-demo', 'IG-live', 'IG-live2', 'IG-live3'],
  },
  // ── Swissquote ────────────────────────────────────────────────────────────
  {
    id: 'SWISSQUOTE',
    name: 'Swissquote',
    displayName: 'Swissquote',
    region: 'EU / Global',
    platform: 'MT4 / MT5',
    execution: 'Market execution',
    minDeposit: '$1,000',
    spread: 'From 1.3 pips',
    highlight: 'Swiss bank regulation',
    description: 'FINMA-regulated Swiss bank offering institutional-grade FX execution and securities custody.',
    tags: ['FINMA', 'Bank-grade', 'Swiss', 'Institutional'],
    categories: ['MT4', 'MT5', 'DMA'],
    accent: 'from-stone-400/20 via-slate-400/10 to-transparent',
    integration: 'MT5',
    servers: ['SWFX Trader', 'Swissquote Bank', 'Swissquote-Demo'],
  },
];
