// Comprehensive demo data for all pages when APIs are unavailable

export const demoStrategies = [
  {
    id: 's1',
    name: 'Momentum Pulse',
    category: 'TREND',
    riskLevel: 'Medium',
    description: 'Capture explosive momentum moves with adaptive pullback entries.',
    creatorId: 'user_alpha',
    creator: {
      fullName: 'Alex Quantum',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AlexQuantum',
      bio: 'Algorithmic trading specialist, 10+ years experience',
    },
    monthlyPrice: 299,
    price: 299,
    isVerified: true,
    copiesCount: 2140,
    subscribers: 2140,
    returns: 68.5,
    sharpe: 1.92,
    drawdown: 12.3,
    equityCurve: Array.from({ length: 24 }).map((_, i) => ({
      date: `M${i + 1}`,
      equity: 100000 + i * 2100 + Math.sin(i / 3) * 5000,
    })),
    totalRevenue: 642300,
  },
  {
    id: 's2',
    name: 'Mean Revert Pro',
    category: 'RANGE',
    riskLevel: 'Low',
    description: 'Statistical mean reversion exploiting overbought/oversold conditions.',
    creatorId: 'user_beta',
    creator: {
      fullName: 'Sarah Markets',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SarahMarkets',
      bio: 'Quantitative analyst, MIT PhD in Finance',
    },
    monthlyPrice: 199,
    price: 199,
    isVerified: true,
    copiesCount: 3420,
    subscribers: 3420,
    returns: 71.2,
    sharpe: 2.14,
    drawdown: 8.7,
    equityCurve: Array.from({ length: 24 }).map((_, i) => ({
      date: `M${i + 1}`,
      equity: 100000 + i * 1800 + Math.cos(i / 2.5) * 3000,
    })),
    totalRevenue: 512480,
  },
  {
    id: 's3',
    name: 'Breakout Matrix',
    category: 'VOLATILITY',
    riskLevel: 'High',
    description: 'Multi-timeframe breakout scanner with advanced risk management.',
    creatorId: 'user_gamma',
    creator: {
      fullName: 'Marcus Volatility',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MarcusVol',
      bio: 'Professional trader, founder of Quant Labs',
    },
    monthlyPrice: 449,
    price: 449,
    isVerified: true,
    copiesCount: 1620,
    subscribers: 1620,
    returns: 64.3,
    sharpe: 1.68,
    drawdown: 18.5,
    equityCurve: Array.from({ length: 24 }).map((_, i) => ({
      date: `M${i + 1}`,
      equity: 100000 + i * 3200 + Math.sin(i / 1.5) * 7000,
    })),
    totalRevenue: 728160,
  },
  {
    id: 's4',
    name: 'Scalp Grid AI',
    category: 'SCALPING',
    riskLevel: 'Very Low',
    description: 'AI-powered micro-scalping with grid trading and hedging.',
    creatorId: 'user_delta',
    creator: {
      fullName: 'Nina AI Trader',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=NinaAI',
      bio: 'Machine learning engineer, specializes in neural network trading',
    },
    monthlyPrice: 399,
    price: 399,
    isVerified: true,
    copiesCount: 2850,
    subscribers: 2850,
    returns: 73.8,
    sharpe: 2.31,
    drawdown: 5.2,
    equityCurve: Array.from({ length: 24 }).map((_, i) => ({
      date: `M${i + 1}`,
      equity: 100000 + i * 950 + Math.sin(i * 0.5) * 1500,
    })),
    totalRevenue: 1137900,
  },
  {
    id: 's5',
    name: 'Arbitrage Sentinel',
    category: 'ARBITRAGE',
    riskLevel: 'Very Low',
    description: 'Cross-exchange arbitrage detector with real-time execution.',
    creatorId: 'user_epsilon',
    creator: {
      fullName: 'David CryptoArb',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=DavidArb',
      bio: 'Crypto trading specialist, 5+ years in digital assets',
    },
    monthlyPrice: 599,
    price: 599,
    isVerified: true,
    copiesCount: 980,
    subscribers: 980,
    returns: 82.1,
    sharpe: 2.64,
    drawdown: 3.1,
    equityCurve: Array.from({ length: 24 }).map((_, i) => ({
      date: `M${i + 1}`,
      equity: 100000 + i * 1450 + Math.cos(i / 3) * 2000,
    })),
    totalRevenue: 588420,
  },
  {
    id: 's6',
    name: 'Institutional VWAP',
    category: 'TREND',
    riskLevel: 'Medium',
    description: 'Volume-weighted average price strategy for larger positions.',
    creatorId: 'user_zeta',
    creator: {
      fullName: 'Emily Institutions',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=EmilyInst',
      bio: 'Former hedge fund PM, 15+ years institutional trading',
    },
    monthlyPrice: 799,
    price: 799,
    isVerified: true,
    copiesCount: 540,
    subscribers: 540,
    returns: 69.5,
    sharpe: 1.87,
    drawdown: 14.2,
    equityCurve: Array.from({ length: 24 }).map((_, i) => ({
      date: `M${i + 1}`,
      equity: 100000 + i * 2800 + Math.sin(i / 2) * 6000,
    })),
    totalRevenue: 431460,
  },
];

export const demoMyStrategies = [
  {
    id: 'my_s1',
    name: 'Custom Momentum v2',
    category: 'TREND',
    riskLevel: 'Medium',
    description: 'My personal tweaked momentum strategy',
    creatorId: 'me',
    creator: {
      fullName: 'You',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=YourStrategy',
    },
    monthlyPrice: 0,
    price: 0,
    isVerified: false,
    copiesCount: 0,
    subscribers: 0,
    returns: 45.2,
    sharpe: 1.34,
    drawdown: 22.1,
    equityCurve: Array.from({ length: 12 }).map((_, i) => ({
      date: `W${i + 1}`,
      equity: 100000 + i * 1200,
    })),
  },
  {
    id: 'my_s2',
    name: 'ML Mean Revert',
    category: 'RANGE',
    riskLevel: 'Low',
    description: 'Machine learning mean reversion model',
    creatorId: 'me',
    creator: {
      fullName: 'You',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=YourStrategy2',
    },
    monthlyPrice: 0,
    price: 0,
    isVerified: false,
    copiesCount: 0,
    subscribers: 0,
    returns: 52.8,
    sharpe: 1.56,
    drawdown: 16.5,
    equityCurve: Array.from({ length: 12 }).map((_, i) => ({
      date: `W${i + 1}`,
      equity: 100000 + i * 850,
    })),
  },
];

export const demoMarketplaceItems = [
  {
    strategyId: 's1',
    strategy: {
      id: 's1',
      name: 'Momentum Pulse',
      category: 'TREND',
      riskLevel: 'Medium',
      description: 'Capture explosive momentum moves with adaptive pullback entries.',
      isVerified: true,
      copiesCount: 2140,
      performance: [{ winRate: 66 }],
      creator: { fullName: 'Alex Quantum' },
    },
    monthlyPrice: 299,
    annualPrice: 2990,
    lifetimePrice: 9990,
    trialDays: 7,
  },
  {
    strategyId: 's2',
    strategy: {
      id: 's2',
      name: 'Mean Revert Pro',
      category: 'RANGE',
      riskLevel: 'Low',
      description: 'Statistical mean reversion exploiting overbought/oversold conditions.',
      isVerified: true,
      copiesCount: 3420,
      performance: [{ winRate: 61 }],
      creator: { fullName: 'Sarah Markets' },
    },
    monthlyPrice: 199,
    annualPrice: 1990,
    lifetimePrice: 5990,
    trialDays: 14,
  },
  {
    strategyId: 's3',
    strategy: {
      id: 's3',
      name: 'Breakout Matrix',
      category: 'VOLATILITY',
      riskLevel: 'High',
      description: 'Multi-timeframe breakout scanner with advanced risk management.',
      isVerified: true,
      copiesCount: 1620,
      performance: [{ winRate: 58 }],
      creator: { fullName: 'Marcus Volatility' },
    },
    monthlyPrice: 449,
    annualPrice: 4490,
    lifetimePrice: 14990,
    trialDays: 7,
  },
  {
    strategyId: 's4',
    strategy: {
      id: 's4',
      name: 'Scalp Grid AI',
      category: 'SCALPING',
      riskLevel: 'Very Low',
      description: 'AI-powered micro-scalping with grid trading and hedging.',
      isVerified: true,
      copiesCount: 2850,
      performance: [{ winRate: 70 }],
      creator: { fullName: 'Nina AI Trader' },
    },
    monthlyPrice: 399,
    annualPrice: 3990,
    lifetimePrice: 11990,
    trialDays: 3,
  },
];

export const demoFeaturedMarketplace = {
  items: [
    {
      strategyId: 's1',
      strategy: {
        id: 's1',
        name: 'Momentum Pulse',
        category: 'TREND',
        riskLevel: 'Medium',
        description: 'Capture explosive momentum moves with adaptive pullback entries.',
        isVerified: true,
        copiesCount: 2140,
        performance: [{ winRate: 66 }],
        creator: { fullName: 'Alex Quantum' },
      },
      monthlyPrice: 299,
      annualPrice: 2990,
      lifetimePrice: 9990,
      trialDays: 7,
    },
    {
      strategyId: 's4',
      strategy: {
        id: 's4',
        name: 'Scalp Grid AI',
        category: 'SCALPING',
        riskLevel: 'Very Low',
        description: 'AI-powered micro-scalping with grid trading and hedging.',
        isVerified: true,
        copiesCount: 2850,
        performance: [{ winRate: 70 }],
        creator: { fullName: 'Nina AI Trader' },
      },
      monthlyPrice: 399,
      annualPrice: 3990,
      lifetimePrice: 11990,
      trialDays: 3,
    },
  ],
  nextCursor: null,
};

export const demoWalletBalance = {
  totalBalance: 125680.42,
  availableBalance: 98450.75,
  reservedBalance: 27229.67,
  currency: 'USD',
};

export const demoWalletTransactions = [
  {
    id: 'tx_001',
    type: 'DEPOSIT',
    status: 'CONFIRMED',
    amount: 50000,
    currency: 'USD',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    reference: 'Bank Transfer - Wells Fargo',
  },
  {
    id: 'tx_002',
    type: 'SUBSCRIPTION_PAYMENT',
    status: 'CONFIRMED',
    amount: -299,
    currency: 'USD',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    reference: 'Momentum Pulse Monthly',
  },
  {
    id: 'tx_003',
    type: 'DEPOSIT',
    status: 'CONFIRMED',
    amount: 25000,
    currency: 'USD',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    reference: 'ACH Transfer',
  },
  {
    id: 'tx_004',
    type: 'SUBSCRIPTION_PAYMENT',
    status: 'CONFIRMED',
    amount: -199,
    currency: 'USD',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    reference: 'Mean Revert Pro Monthly',
  },
  {
    id: 'tx_005',
    type: 'WITHDRAWAL',
    status: 'PENDING',
    amount: -10000,
    currency: 'USD',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    reference: 'Bank Transfer - Chase',
  },
];

export const demoDashboardMetrics = {
  portfolioValue: 125680.42,
  availableBalance: 98450.75,
  totalProfit: 24580.50,
  dailyReturn: 2.4,
  weeklyReturn: 8.6,
  monthlyReturn: 12.4,
  activeStrategies: 4,
  totalTrades: 412,
  winRate: 63.2,
  sharpeRatio: 1.84,
  maxDrawdown: 8.6,
  equityCurve: Array.from({ length: 30 }).map((_, i) => ({
    date: `D${i + 1}`,
    equity: 100000 + i * 850 + Math.sin(i / 5) * 2000,
    profit: i * 850,
  })),
};
