export enum ErrorCode {
  // Auth
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  OTP_EXPIRED = 'OTP_EXPIRED',
  OTP_INVALID = 'OTP_INVALID',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_REFRESH_SESSION = 'INVALID_REFRESH_SESSION',
  REFRESH_TOKEN_REVOKED = 'REFRESH_TOKEN_REVOKED',
  INVALID_RESET_LINK = 'INVALID_RESET_LINK',
  SUPABASE_AUTH_FAILED = 'SUPABASE_AUTH_FAILED',
  EMAIL_MISMATCH = 'EMAIL_MISMATCH',

  // General
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // Trading / Strategies
  STRATEGY_NOT_FOUND = 'STRATEGY_NOT_FOUND',
  BROKER_NOT_CONNECTED = 'BROKER_NOT_CONNECTED',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',

  // Wallet
  WITHDRAW_LIMIT_EXCEEDED = 'WITHDRAW_LIMIT_EXCEEDED',
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',

  // Marketplace
  LISTING_NOT_FOUND = 'LISTING_NOT_FOUND',
  ALREADY_SUBSCRIBED = 'ALREADY_SUBSCRIBED',

  // Admin
  USER_ALREADY_SUSPENDED = 'USER_ALREADY_SUSPENDED',
}
