import { StrategyDefinition } from '../types';

function sym(id: string): string {
  return id.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^[0-9]/, '_s');
}

export function generateMql5(def: StrategyDefinition): string {
  const lines: string[] = [];
  const risk = def.risk ?? {};
  const name = def.name.replace(/"/g, "'");

  lines.push(
    '//+------------------------------------------------------------------+',
  );
  lines.push(`//| Expert Advisor: ${name}`);
  lines.push('//| Generated by Profytron Strategy Builder');
  lines.push(
    '//+------------------------------------------------------------------+',
  );
  lines.push('#property copyright "Profytron"');
  lines.push('#property version   "1.00"');
  lines.push('#include <Trade\\Trade.mqh>');
  lines.push('');
  lines.push(
    `input double InpRiskPct = ${risk.riskPerTradePct ?? 1};   // Risk per trade (% of equity)`,
  );
  lines.push(
    `input double InpSLPct   = ${risk.slPct ?? 1};             // Stop Loss (%)`,
  );
  lines.push(
    `input double InpTPPct   = ${risk.tpPct ?? 2};             // Take Profit (%)`,
  );
  lines.push('');

  // Indicator handles
  for (const [refId, cfg] of Object.entries(def.indicators)) {
    const v = sym(refId);
    switch (cfg.type) {
      case 'SMA':
      case 'EMA': {
        const mode = cfg.type === 'SMA' ? 'MODE_SMA' : 'MODE_EMA';
        lines.push(`int h_${v};`);
        break;
      }
      case 'RSI':
        lines.push(`int h_${v};`);
        break;
      case 'MACD':
        lines.push(`int h_${v};`);
        break;
      case 'BOLLINGER':
        lines.push(`int h_${v};`);
        break;
      case 'ATR':
        lines.push(`int h_${v};`);
        break;
    }
  }

  lines.push('CTrade trade;');
  lines.push('');

  // OnInit
  lines.push('int OnInit()');
  lines.push('{');
  for (const [refId, cfg] of Object.entries(def.indicators)) {
    const v = sym(refId);
    switch (cfg.type) {
      case 'SMA':
        lines.push(
          `   h_${v} = iMA(_Symbol, PERIOD_CURRENT, ${cfg.period ?? 14}, 0, MODE_SMA, PRICE_CLOSE);`,
        );
        break;
      case 'EMA':
        lines.push(
          `   h_${v} = iMA(_Symbol, PERIOD_CURRENT, ${cfg.period ?? 14}, 0, MODE_EMA, PRICE_CLOSE);`,
        );
        break;
      case 'RSI':
        lines.push(
          `   h_${v} = iRSI(_Symbol, PERIOD_CURRENT, ${cfg.period ?? 14}, PRICE_CLOSE);`,
        );
        break;
      case 'MACD':
        lines.push(
          `   h_${v} = iMACD(_Symbol, PERIOD_CURRENT, ${cfg.fastPeriod ?? 12}, ${cfg.slowPeriod ?? 26}, ${cfg.signalPeriod ?? 9}, PRICE_CLOSE);`,
        );
        break;
      case 'BOLLINGER':
        lines.push(
          `   h_${v} = iBands(_Symbol, PERIOD_CURRENT, ${cfg.period ?? 20}, 0, ${cfg.stdDevMultiplier ?? 2}, PRICE_CLOSE);`,
        );
        break;
      case 'ATR':
        lines.push(
          `   h_${v} = iATR(_Symbol, PERIOD_CURRENT, ${cfg.period ?? 14});`,
        );
        break;
    }
  }
  lines.push('   return(INIT_SUCCEEDED);');
  lines.push('}');
  lines.push('');

  // OnDeinit
  lines.push('void OnDeinit(const int reason)');
  lines.push('{');
  for (const [refId] of Object.entries(def.indicators)) {
    lines.push(`   IndicatorRelease(h_${sym(refId)});`);
  }
  lines.push('}');
  lines.push('');

  // OnTick
  lines.push('void OnTick()');
  lines.push('{');
  lines.push('   if(PositionsTotal() > 0) return;');
  lines.push('');

  for (const [refId] of Object.entries(def.indicators)) {
    const v = sym(refId);
    lines.push(`   double ${v} = GetIndicatorValue(h_${v}, 0);`);
    lines.push(`   double ${v}_prev = GetIndicatorValue(h_${v}, 1);`);
  }
  lines.push('');
  lines.push('   double price = iClose(_Symbol, PERIOD_CURRENT, 0);');
  lines.push('   double sl    = price * InpSLPct / 100.0;');
  lines.push('   double tp    = price * InpTPPct / 100.0;');
  lines.push(
    '   double lots  = AccountInfoDouble(ACCOUNT_EQUITY) * InpRiskPct / 100.0 / (sl * 100000);',
  );
  lines.push('   lots = MathMax(0.01, NormalizeDouble(lots, 2));');
  lines.push('');
  lines.push('   // TODO: replace "true" with your compiled entry conditions');
  if (def.direction !== 'SHORT') {
    lines.push('   if(true /* long entry condition */)');
    lines.push(
      `      trade.Buy(lots, _Symbol, 0, price - sl, price + tp, "${name} Long");`,
    );
  }
  if (def.direction !== 'LONG') {
    lines.push('   if(true /* short entry condition */)');
    lines.push(
      `      trade.Sell(lots, _Symbol, 0, price + sl, price - tp, "${name} Short");`,
    );
  }
  lines.push('}');
  lines.push('');
  lines.push('double GetIndicatorValue(int handle, int shift)');
  lines.push('{');
  lines.push('   double buf[];');
  lines.push('   ArraySetAsSeries(buf, true);');
  lines.push('   if(CopyBuffer(handle, 0, shift, 1, buf) < 1) return 0;');
  lines.push('   return buf[0];');
  lines.push('}');

  return lines.join('\n');
}
